name: mighty_fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1.2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  lottie: ^3.1.3

  #Network
  http: ^1.2.2
  connectivity_plus: ^6.0.4

  #State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #Storage
  shared_preferences: ^2.3.1

  #Audio
  just_audio: ^0.9.41

  #calendar
  table_calendar: ^3.1.2

  syncfusion_flutter_datepicker: ^26.2.13


  # Firebase
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.3

  #login
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1


  flutter_toggle_tab: 1.4.1

  #one signal
  onesignal_flutter: 5.2.2

  #notification
  awesome_notifications: ^0.9.3+1

  #Video player
  youtube_player_flutter: ^8.1.2
  chewie: 1.8.1

  #ads
  google_mobile_ads: ^5.1.0

  #step count
  pedometer: ^4.0.2

  #gpt
  chat_gpt_flutter: ^1.0.16
  chat_gpt_sdk: ^3.1.0


  #Other
  fluttertoast: ^8.2.6
  country_code_picker: ^3.1.0
  infinite_listview: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_html:
    git:
      url: https://github.com/appmeetmighty/flutter_html.git
  flutter_tts: ^4.0.2
  draggable_bottom_sheet: ^1.0.2
  share_plus: ^10.0.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1
  simple_pip_mode: ^0.8.0
  photo_view: ^0.15.0
  tuple: ^2.0.2

  #localizations
  flutter_localizations:
    sdk: flutter

  #chart
  syncfusion_flutter_charts: ^26.2.14
  path_provider: ^2.1.4

  #payment
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^11.0.0
  bambara_flutter: ^0.0.6
  flutter_paystack:
    git:
      url: https://github.com/appmeetmighty/flutter_paystack/
  flutter_braintree: ^4.0.0
  flutterwave_standard: ^1.0.7
  flutter_paytabs_bridge: ^2.6.18
  paytm_allinonesdk: ^1.2.6
  my_fatoorah: ^3.3.0
  #flutter_inappwebview: ^5.8.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  webview_flutter: ^4.8.0
  #flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
    - assets/loading.json
